FROM python:3.9
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY server/requirements.txt /app/
RUN pip install -r requirements.txt
RUN apt-get update
RUN apt-get install -y ffmpeg
# install gsutil for pulling flac demo
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

COPY . /app/
# RUN ll -ah