# Generated by Django 3.2.9 on 2021-11-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.IntegerField()),
                ('base_date_time', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('vessel_type', models.IntegerField()),
                ('boat_type', models.CharField(max_length=32)),
            ],
        ),
    ]
